#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("AndroidAltBeaconLibrary.Sample.Resource", IsApplication=true)]

namespace AndroidAltBeaconLibrary.Sample
{
	
	
	[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Color
		{
			
			// aapt resource value: 0x7F010000
			public const int custom_theme_color = 2130771968;
			
			// aapt resource value: 0x7F010001
			public const int text_theme_color = 2130771969;
			
			static Color()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Color()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7F020000
			public const int altbeacon = 2130837504;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7F030000
			public const int backgroundButton = 2130903040;
			
			// aapt resource value: 0x7F030001
			public const int beaconDistance = 2130903041;
			
			// aapt resource value: 0x7F030002
			public const int beaconId = 2130903042;
			
			// aapt resource value: 0x7F030003
			public const int layout = 2130903043;
			
			// aapt resource value: 0x7F030004
			public const int list = 2130903044;
			
			// aapt resource value: 0x7F030005
			public const int startButton = 2130903045;
			
			// aapt resource value: 0x7F030006
			public const int stopButton = 2130903046;
			
			// aapt resource value: 0x7F030007
			public const int textView1 = 2130903047;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7F040000
			public const int ActivityBackground = 2130968576;
			
			// aapt resource value: 0x7F040001
			public const int ListItem = 2130968577;
			
			// aapt resource value: 0x7F040002
			public const int MainActivity = 2130968578;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7F050000
			public const int app_name = 2131034112;
			
			// aapt resource value: 0x7F050001
			public const int hello = 2131034113;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7F060000
			public const int CustomActionBar = 2131099648;
			
			// aapt resource value: 0x7F060001
			public const int CustomTheme = 2131099649;
			
			// aapt resource value: 0x7F060002
			public const int Theme_AltBeacon = 2131099650;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
	}
}
#pragma warning restore 1591
