<?xml version="1.0" encoding="utf-8"?>
<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
	<TargetFramework>net9.0-android</TargetFramework>
    <Configuration Condition=" '$(Configuration)' == '' ">Debug</Configuration>
    <OutputType>Library</OutputType>
    <RootNamespace>AndroidAltBeaconLibrary</RootNamespace>
    <AssemblyName>AndroidAltBeaconLibrary</AssemblyName>

    <!-- NuGet Package Properties -->
    <PackageId>AndroidAltBeaconLibrary</PackageId>
    <Authors>AltBeacon.org</Authors>
    <Owners>Chris Riesgo, Anton Yaroshenko</Owners>
    <PackageProjectUrl>https://github.com/stepkillah/Android-AltBeacon-Library</PackageProjectUrl>
    <PackageRequireLicenseAcceptance>false</PackageRequireLicenseAcceptance>
    <Description>A .NET Android and MAUI library providing APIs to interact with beacons. Supports .NET 9 and MAUI.</Description>
    <PackageReleaseNotes>Updated to .NET 9 and MAUI support, binding version 2.21.1 of android-beacon-library</PackageReleaseNotes>
    <Copyright>Copyright 2024</Copyright>
    <PackageTags>android libraries altbeacon beacon ibeacon maui dotnet9</PackageTags>
    <RepositoryType>git</RepositoryType>
    <RepositoryUrl>https://github.com/stepkillah/Android-AltBeacon-Library</RepositoryUrl>
    <GeneratePackageOnBuild>false</GeneratePackageOnBuild>
    <IsPackable>true</IsPackable>
  </PropertyGroup>

	
  <ItemGroup>
	  <AndroidMavenLibrary Include="org.altbeacon:android-beacon-library" Version="2.21.1" />
  </ItemGroup>

	
  <ItemGroup>
    <PackageReference Include="Xamarin.AndroidX.AppCompat" Version="1.7.1.1" />
    <PackageReference Include="Xamarin.AndroidX.Core.Core.Ktx" Version="1.17.0" />
    <PackageReference Include="Xamarin.AndroidX.Lifecycle.Process" Version="2.9.3" />
    <PackageReference Include="Xamarin.Kotlin.StdLib.Jdk7" Version="2.2.10" />
    <AndroidNamespaceReplacement Include="org.altbeacon" Replacement="AltBeaconOrg" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Properties\" />
  </ItemGroup>
  <ItemGroup>
    <TransformFile Include="Transforms\EnumFields.xml" />
    <TransformFile Include="Transforms\EnumMethods.xml" />
    <TransformFile Include="Transforms\Metadata.xml" />
  </ItemGroup>
</Project>