name: Build .NET Android MAUI

on: [push]

jobs:
  build:

    runs-on: macos-latest

    env:
      PackVersion: "2.21.1"

    steps:
    - uses: actions/checkout@v4

    - name: Setup .NET 9
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '9.0.x'

    - name: Install MAUI workloads
      run: dotnet workload install maui-android

    - name: Restore dependencies
      run: dotnet restore AndroidAltBeaconLibrary/AndroidAltBeaconLibrary.sln

    - name: Build
      run: dotnet build AndroidAltBeaconLibrary/AndroidAltBeaconLibrary/AndroidAltBeaconLibrary.csproj --configuration Release --no-restore /p:VersionNumber=$PackVersion.$GITHUB_RUN_ID /p:Version=$PackVersion.$GITHUB_RUN_ID
   
    - name: Pack NuGet
      run: dotnet pack AndroidAltBeaconLibrary/AndroidAltBeaconLibrary/AndroidAltBeaconLibrary.csproj --configuration Release --no-build --output ./nuget_pack /p:PackageVersion=$PackVersion.$GITHUB_RUN_ID

    - name: Push NuGet
      run: dotnet nuget push ./nuget_pack/*.nupkg --source https://nuget.pkg.github.com/stepkillah/index.json --api-key ${{secrets.GITHUB_TOKEN}} --skip-duplicate
