name: Build Xamarin.Android

on: [push]

jobs:
  build:

    runs-on: macos-latest
    
    env:
      PackVersion: "2.17.1"

    steps:
    - uses: actions/checkout@v2
    - name: Set default Xamarin SDK versions
      run: |
        $VM_ASSETS/select-xamarin-sdk-v2.sh --mono=6.12 --android=11.1

    - name: Setup .NET Core SDK 5.0.x
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '5.0.x'

    - name: Install dependencies
      run: nuget restore AndroidAltBeaconLibrary/AndroidAltBeaconLibrary.sln

    - name: Build
      run: msbuild AndroidAltBeaconLibrary/AndroidAltBeaconLibrary/AndroidAltBeaconLibrary.csproj /p:Configuration=Release
   
    - name: Nuget Pack
      run: nuget pack ./NuGet/AndroidAltBeaconLibrary.nuspec -OutputDirectory ./nuget_pack -version $PackVersion.$GITHUB_RUN_ID

    - name: Nuget Push
      run: nuget push ./nuget_pack/*.nupkg  -s https://nuget.pkg.github.com/stepkillah/index.json -k ${{secrets.GITHUB_TOKEN}} --skip-duplicate --no-symbols true
