name: Build .NET Android MAUI

on: [push]

jobs:
  build:

    runs-on: macos-latest

    env:
      PackVersion: "2.21.1"

    steps:
    - uses: actions/checkout@v4

    - name: Setup .NET 9
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '9.0.x'

    - name: Install MAUI workloads
      run: dotnet workload install maui-android

    - name: Restore dependencies
      run: dotnet restore AndroidAltBeaconLibrary/AndroidAltBeaconLibrary.csproj

    - name: Build
      run: dotnet build AndroidAltBeaconLibrary/AndroidAltBeaconLibrary.csproj --configuration Release --no-restore /p:VersionNumber=$PackVersion.$GITHUB_RUN_ID /p:Version=$PackVersion.$GITHUB_RUN_ID
   
    - name: Nuget Pack
      run: nuget pack ./NuGet/AndroidAltBeaconLibrary.nuspec -OutputDirectory ./nuget_pack -version $PackVersion.$GITHUB_RUN_ID

    - name: Nuget Push
      run: nuget push ./nuget_pack/*.nupkg -Source https://nuget.pkg.github.com/stepkillah/index.json -ApiKey ${{secrets.GITHUB_TOKEN}} -SkipDuplicate -NoSymbols
